fullnameOverride: "hyperf-skeleton"
namespace: hyperf-skeleton

deployment:
  containers:
  - name: hyperf-skeleton
    image:
      repository: thiagofaino/hyperf-skeleton
      tag: "c14152ca-1b82-4906-8013-0c2d91dd37bf"

    ports:
    - name: http
      protocol: TCP
      containerPort: 8080
      servicePort: 9501

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-external
    # kubernetes.io/tls-acme: "true"
  paths:
    - path: /
      servicePort: http
  hosts:
    - hyperf-skeleton.local
#  tls:
#  - secretName: chart-example-tls
#    hosts:
#    - chart-example.local
